# The fishman diaries
baseURL = "https://karetsu.github.io/diaries"
languageCode = "en-gb"
DefaultContentLanguage = "en"
title = "the fishman diaries"
theme = "meghna"
pygmentsUseClasses = true # syntax highlighting
summaryLength = 10
publishDir="docs"
rssLimit = 10
enableEmoji = true  # Shorthand emojis in content files - https://gohugo.io/functions/emojify/

[taxonomies]
  author = "author"
  category = "categories"
  tag = "tags"


[markup]
  [markup.highlight]
    codeFences = true
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    style = "algol"
    tabWidth = 2


# Menu
[menu]
    [[menu.nav]]
    name = "Archive"
    URL = "blog"
    weight = 3

    [[menu.nav]]
    name = "About Us"
    URL = "about"
    weight = 2

    [[menu.nav]]
    name = "Contributors"
    URL = "our-team"
    weight = 4

# Site params
[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"
  home= "Home"
  logo = "images/logo_small.png"
  # Meta data
  description = "<3"
  author = "Aloysius"
  code_copy_button = true
  # Google Analitycs
  custom_css = ["css/custom.css"]

    # counter
    [params.counter]
    enable = true
    bgImage = "images/backgrounds/bg-1.jpg"
        [[params.counter.counterItem]]
        title = "Open issues"
        icon = "tf-ion-android-sad"
        count = "10"
        [[params.counter.counterItem]]
        title = "Posts"
        icon = "tf-ion-bookmark"
        count = "30"
        [[params.counter.counterItem]]
        title = "Contributors"
        icon = "tf-ion-ios-contact"
        count = "3"
        [[params.counter.counterItem]]
        title = "Version"
        icon = "tf-ion-android-happy"
        count = "0.9"


    [params.preloader]
    enable = true
    preloader = "images/cthulu.jpg"


    # Banner Section
    [params.banner]
    enable = true
    bgImage = "images/cthulu.jpg"
    heading = "The Fishman Diaries"
    content= "A curated archive of interesting blogs and papers"
    btn = true
    btnText="Read posts"
    btnURL="posts/"


    # footer
    [params.footer]
        copyright = "Aloysius"
        copyrightURL = "https://github.com/karetsu"

        [[params.footer.socialIcon]]
        icon = "tf-ion-social-rss"
        url = "index.xml"
