# The fishman diaries
baseURL = "https://karetsu.github.io/diaries"
languageCode = "en-gb"
DefaultContentLanguage = "en"
title = "the fishman diaries"
theme = "meghna"
pygmentsUseClasses = true # syntax highlighting
summaryLength = 10
publishDir="docs"
rssLimit = 10
enableEmoji = true  # Shorthand emojis in content files - https://gohugo.io/functions/emojify/

[taxonomies]
  author = "author"
  category = "categories"
  tag = "tags"


[markup]
  [markup.highlight]
    codeFences = true
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    style = "algol"
    tabWidth = 2

# Menu
[menu]
    [[menu.nav]]
    name = "Blog"
    URL = "blog"
    weight = 3

    [[menu.nav]]
    name = "About Us"
    URL = "about"
    weight = 2

# Site params
[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"
  home= "Home"
  logo = "images/logo_small.png"
  # Meta data
  description = "<3"
  author = "Aloysius"
  code_copy_button = true
  # Google Analitycs
  custom_css = ["css/custom.css"]

    # Banner Section
    [params.banner]
    enable = true
    bgImage = "images/cthulu.jpg"
    #icon = "tf-ion-play"
    heading = "The Fishman Diaries"
    content= "A curated archive of interesting blogs and papers"
    btn = true
    btnText="Read posts"
    btnURL="posts/"

    # footer
    [params.footer]
        copyright = "Aloysius"
        copyrightURL = "https://github.com/karetsu"
